BeerOverflow/BeerOverflowAPI/Controllers/BeersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerOverflow.Models;
using Database;
using Services.Contracts;
using BeerOverflowAPI.ViewMappers;
using BeerOverflowAPI.Models;
using System.Security.Claims;
using Services;
using Services.DTOs;
using Microsoft.AspNetCore.Authorization;

namespace BeerOverflowAPI.Controllers
{
    public class BeersController : Controller
    {
        private readonly IBeerService _service;
        private readonly IUsersService _usersService;
        private readonly IBreweryService _breweryService;
        private readonly ICountriesService _countriesService;
        private readonly IBeerStylesService _beerStylesService;
        public BeersController(IBeerService service,
                            IUsersService usersService,
                            IBreweryService breweryService,
                            ICountriesService countriesService,
            IBeerStylesService _beerStylesService)
        {
            this._service = service ?? throw new ArgumentNullException(nameof(service));
            this._usersService = usersService ?? throw new ArgumentNullException(nameof(service)); ;
            this._breweryService = breweryService ?? throw new ArgumentNullException(nameof(service)); 
            this._countriesService = countriesService ?? throw new ArgumentNullException(nameof(service)); ;
            this._beerStylesService = _beerStylesService ?? throw new ArgumentNullException(nameof(service)); ;
        }



        // GET: Beers
        public async Task<IActionResult> Index(string searchString)
        {
            // TODO: Approach for Wishing beer:
            //var temp = this.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            //Console.WriteLine(temp);
            // _usersService.Wish (temp, beerID); // 

            IEnumerable<BeerDTO> beers = null;
            if (!String.IsNullOrEmpty(searchString))
            {
                beers = await _service.Search(searchString);
            }
            else
            {
                beers = await _service.GetAllAsync();
            }
            if (!User.IsInRole("admin"))
            {
                beers = beers.Where(b => b.IsDeleted == false).ToList();
            }

            var beersDTO = beers.Select(b => b.MapBeerDTOToView());

            return View(beersDTO);
        }

        // GET: Beers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await this._service.GetAsync(id);
            if (beer == null)
            {
                return NotFound();
            }

            return View(beer.MapBeerDTOToView());
        }

        [Authorize]
        // GET: Beers/Create
        public IActionResult Create()
        {
            ViewData["BreweryID"] = new SelectList( this._breweryService.GetAllAsync().Result, "ID", "Name");
            ViewData["CountryID"] = new SelectList(this._countriesService.GetAllAsync().Result, "ID", "Name");
            ViewData["StyleID"] = new SelectList(this._beerStylesService.GetAllAsync().Result, "ID", "Name");
            return View();
        }
        
        // POST: Beers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Name,ABV,StyleID,CountryID,BreweryID,Rating")] BeerViewModel beer)
        {
            if (ModelState.IsValid)
            {
                var theNewBeer = await this._service.CreateAsync(beer.MapBeerViewToDTO());
                beer = theNewBeer.MapBeerDTOToView();
                return RedirectToAction(nameof(Index));
            }

            ViewData["BreweryID"] = new SelectList(this._breweryService.GetAllAsync().Result, "ID", "Name");
            ViewData["CountryID"] = new SelectList(this._countriesService.GetAllAsync().Result, "ID", "Name");
            ViewData["StyleID"] = new SelectList(this._beerStylesService.GetAllAsync().Result, "ID", "Name");
            return View(beer);
        }
        /*
        // GET: Beers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beers.FindAsync(id);
            if (beer == null)
            {
                return NotFound();
            }
            ViewData["BreweryID"] = new SelectList(_context.Breweries, "ID", "Name", beer.BreweryID);
            ViewData["CountryID"] = new SelectList(_context.Countries, "ID", "Name", beer.CountryID);
            ViewData["StyleID"] = new SelectList(_context.BeerStyles, "ID", "Description", beer.StyleID);
            return View(beer);
        }
        
        // POST: Beers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("ID,Name,ABV,StyleID,CountryID,BreweryID,Rating,CreatedOn,ModifiedOn,DeletedOn,IsDeleted")] Beer beer)
        {
            if (id != beer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(beer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BeerExists(beer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreweryID"] = new SelectList(_context.Breweries, "ID", "Name", beer.BreweryID);
            ViewData["CountryID"] = new SelectList(_context.Countries, "ID", "Name", beer.CountryID);
            ViewData["StyleID"] = new SelectList(_context.BeerStyles, "ID", "Description", beer.StyleID);
            return View(beer);
        }
        */

        // GET: Beers/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await this._service.GetAsync(id);
            if (beer == null)
            {
                return NotFound();
            }
            return View(beer.MapBeerDTOToView());

            //return RedirectToAction(nameof(Index));
        }

        // POST: Beers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var result = await this._service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

BeerOverflow/BeerOverflowAPI/Controllers/BreweryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerOverflow.Models;
using Database;
using Services;
using BeerOverflowAPI.ViewMappers;
using BeerOverflowAPI.Models;
using Services.Mappers;
using Services.Contracts;
using Microsoft.AspNetCore.Authorization;

namespace BeerOverflowAPI.Controllers
{
    public class BreweryController : Controller
    {
        private readonly IBreweryService _service;
        private readonly ICountriesService _countryService;

        public BreweryController(IBreweryService service, ICountriesService _countryService)
        {
            this._service = service ?? throw new ArgumentNullException(nameof(service)); ;
            this._countryService = _countryService ?? throw new ArgumentNullException(nameof(service));
        }

        // GET: Breweries
        public async Task<IActionResult> Index()
        {
            var index = await _service.GetAllAsync();
            return View(index.Select(b => b.MapBreweryDTOToView()));
        }

        // GET: Breweries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var brewery = await _service.GetAsync(id);
            if (brewery == null)
            {
                return NotFound();
            }

            return View(brewery.MapBreweryDTOToView());
        }

        // GET: Breweries/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["CountryID"] = new SelectList(this._countryService.GetAllAsync().Result, "ID", "Name");
            return View();
        }

        // POST: Breweries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("ID,Name,CountryID")] BreweryViewModel brewery)
        {
            if (ModelState.IsValid)
            {
                var newBrewery = await _service.CreateAsync(brewery.MapBreweryViewToDTO());
                //_context.Add(brewery);
                //await _context.SaveChangesAsync();
                brewery = newBrewery.MapBreweryDTOToView();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CountryID"] = new SelectList(this._countryService.GetAllAsync().Result, "ID", "Name", brewery.Name);
            return View(brewery);
        }

        // GET: Breweries/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brewery = await _service.GetAsync(id);
            if (brewery == null)
            {
                return NotFound();
            }
            ViewData["CountryID"] = new SelectList(this._countryService.GetAllAsync().Result, "ID", "Name", brewery.CountryID);
            return View(brewery.MapBreweryDTOToView());
        }

        // POST: Breweries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,CountryID,IsDeleted")] BreweryViewModel brewery)
        {
            if (id != brewery.ID)
            {
                return NotFound();
            }
            var updateModel = brewery.MapBreweryViewToDTO();
            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(id, updateModel);
                }
                catch (Exception)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CountryID"] = new SelectList(this._countryService.GetAllAsync().Result, "ID", "Name", brewery.CountryID);
            return View(brewery);
        }

        // GET: Breweries/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brewery = await _service.GetAsync(id);
            if (brewery == null)
            {
                return NotFound();
            }

            return View(brewery.MapBreweryDTOToView());
        }

        // POST: Breweries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brewery = await _service.GetAsync(id);
            bool result;
            try
            {
                result = await _service.DeleteAsync(id);
            }
            catch (Exception)
            {

                return NotFound();
            }
            if (result)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return BadRequest();
            }
        }


        [Authorize]
        public async Task<IActionResult> Recover(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var brewery = await _service.GetAsync(id);
            if (brewery == null)
            {
                return NotFound();
            }
            return View(brewery.MapBreweryDTOToView());
        }

        [HttpPost, ActionName("Recover")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> RecoverConfirmed(int id)
        {
            try
            {
                var brewery = await _service.GetAsync(id);
                await _service.CreateAsync(brewery);
            }
            catch (Exception)
            {
                return BadRequest();
            }
            return RedirectToAction("Index");
        }
    }
}

BeerOverflow/BeerOverflowAPI/Views/Shared/_Layout _side.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeerOverflow - Team Carlsberg</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<!-- <body>
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
         <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeerOverflow</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                 aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>
     </nav>

 <div class="container-fluid" style="width:25%">

     <ul class="nav flex-column">
         <li class="nav-item">
             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
         </li>
         <li class="nav-item">
             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
         </li>
         <li class="nav-item">
             <a class="nav-link text-dark" asp-area="" asp-controller="Brewery" asp-action="Index">Breweries</a>
         </li>
         <li class="nav-item">
             <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
         </li>
     </ul>
 </div>
 -->
<body>










































    <div class=" flex-wrap">
        <a href="/">
            <div class="navbar navbar-inverse navbar-fixed-top" style="width:20%"></div>
            <img src="~/BO_Logo/Logo_text.svg" style="width:20%">
        </a>
        <nav class="navbar navbar-inverse navbar-fixed-top" style="width:20%">
            <div class="container-fluid nav flex-column">
                <partial name="_LoginPartial"   />
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Beers" asp-action="Index">Beers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="BeerStyles" asp-action="Index">Styles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Brewery" asp-action="Index">Breweries</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                    </li>

                    <!--<partial name="_LoginPartial" />-->
                </ul>
            </div>
        </nav>

        <div class="container body-content fixed-top" style=" margin-left:20% ;width:80%">

            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - BeerOverflow - Team Carslberg <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>

BeerOverflow/BeerOverflowAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeerOverflow - Team Carlsberg</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<!-- <body>
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
         <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeerOverflow</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                 aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>
     </nav>

 <div class="container-fluid" style="width:25%">

     <ul class="nav flex-column">
         <li class="nav-item">
             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
         </li>
         <li class="nav-item">
             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
         </li>
         <li class="nav-item">
             <a class="nav-link text-dark" asp-area="" asp-controller="Brewery" asp-action="Index">Breweries</a>
         </li>
         <li class="nav-item">
             <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
         </li>
     </ul>
 </div>
 -->
<body>

    <div class="container">
        <div class="row">
            <div class="col-sm-3" role="complementary">
                <nav class="float-left">
                    <ul class="nav flex-column">
                        <!-- Logo -->
                        <li>
                            <div class="logo-wrapper">
                                <a href="/">
                                    <img src="~/BO_Logo/Logo_text.svg"
                                         class="img-fluid flex-center">
                                </a>
                            </div>
                        </li>
                        <!--/. Logo -->
                        <partial name="_LoginPartial" />
                        <li role="separator" class="divider"></li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-primary text-dark" asp-area="" asp-controller="Beers" asp-action="Index">Beers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-primary text-dark" asp-area="" asp-controller="BeerStyles" asp-action="Index">Styles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-primary text-dark" asp-area="" asp-controller="Brewery" asp-action="Index">Breweries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-primary text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                        </li>
                    </ul>
                    <!-- Search form -->
                    <form asp-controller="Beers" asp-action="Index">
                        <p>
                            <input type="text" name="SearchString">
                            <input type="submit" value="Search" class="btn btn-primary" />
                        </p>
                    </form>
                    <!--/. Search form -->
                </nav>
            </div>

            <div class="col-md-9" role="main">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - BeerOverflow - Team Carslberg <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>