BeerOverflow/BeerOverflowAPI/Models/ReviewViewModel.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace BeerOverflowAPI.Models
{
    public class ReviewViewModel
    {

        public int? ID { get; set; }
        public int? BeerID { get; set; }
        public string BeerName { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public int Rating { get; set; }
        public string Description { get; set; }
        public int LikesCount { get; set; }
        public ICollection<CommentViewModel> Comments { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsFlagged { get; set; }

    }
}

BeerOverflow/BeerOverflowAPI/Controllers/BeersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerOverflow.Models;
using Database;
using Services.Contracts;
using BeerOverflowAPI.ViewMappers;
using BeerOverflowAPI.Models;
using System.Security.Claims;
using Services;
using Services.DTOs;
using Microsoft.AspNetCore.Authorization;

namespace BeerOverflowAPI.Controllers
{
    public class BeersController : Controller
    {
        private readonly IBeerService _service;
        private readonly IUsersService _usersService;
        private readonly IBreweryService _breweryService;
        private readonly ICountriesService _countriesService;
        private readonly IBeerStylesService _beerStylesService;
        public BeersController(IBeerService service,
                            IUsersService usersService,
                            IBreweryService breweryService,
                            ICountriesService countriesService,
            IBeerStylesService _beerStylesService)
        {
            this._service = service ?? throw new ArgumentNullException(nameof(service));
            this._usersService = usersService ?? throw new ArgumentNullException(nameof(service)); ;
            this._breweryService = breweryService ?? throw new ArgumentNullException(nameof(service)); 
            this._countriesService = countriesService ?? throw new ArgumentNullException(nameof(service)); ;
            this._beerStylesService = _beerStylesService ?? throw new ArgumentNullException(nameof(service)); ;
        }



        // GET: Beers
        public async Task<IActionResult> Index(string searchString)
        {
            // TODO: Approach for Wishing beer:
            //var temp = this.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            //Console.WriteLine(temp);
            // _usersService.Wish (temp, beerID); // 

            IEnumerable<BeerDTO> beers = null;
            if (!String.IsNullOrEmpty(searchString))
            {
                beers = await _service.Search(searchString);
            }
            else
            {
                beers = await _service.GetAllAsync();
            }
            if (!User.IsInRole("admin"))
            {
                beers = beers.Where(b => b.IsDeleted == false).ToList();
            }

            var beersDTO = beers.Select(b => b.MapBeerDTOToView());

            return View(beersDTO);
        }

        // GET: Beers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await this._service.GetAsync(id);
            if (beer == null)
            {
                return NotFound();
            }

            return View(beer.MapBeerDTOToView());
        }

        [Authorize]
        // GET: Beers/Create
        public IActionResult Create()
        {
            ViewData["BreweryID"] = new SelectList( this._breweryService.GetAllAsync().Result, "ID", "Name");
            ViewData["CountryID"] = new SelectList(this._countriesService.GetAllAsync().Result, "ID", "Name");
            ViewData["StyleID"] = new SelectList(this._beerStylesService.GetAllAsync().Result, "ID", "Name");
            return View();
        }
        
        // POST: Beers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Name,ABV,StyleID,CountryID,BreweryID,Rating")] BeerViewModel beer)
        {
            if (ModelState.IsValid)
            {
                var theNewBeer = await this._service.CreateAsync(beer.MapBeerViewToDTO());
                beer = theNewBeer.MapBeerDTOToView();
                return RedirectToAction(nameof(Index));
            }

            ViewData["BreweryID"] = new SelectList(this._breweryService.GetAllAsync().Result, "ID", "Name");
            ViewData["CountryID"] = new SelectList(this._countriesService.GetAllAsync().Result, "ID", "Name");
            ViewData["StyleID"] = new SelectList(this._beerStylesService.GetAllAsync().Result, "ID", "Name");
            return View(beer);
        }
        /*
        // GET: Beers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beers.FindAsync(id);
            if (beer == null)
            {
                return NotFound();
            }
            ViewData["BreweryID"] = new SelectList(_context.Breweries, "ID", "Name", beer.BreweryID);
            ViewData["CountryID"] = new SelectList(_context.Countries, "ID", "Name", beer.CountryID);
            ViewData["StyleID"] = new SelectList(_context.BeerStyles, "ID", "Description", beer.StyleID);
            return View(beer);
        }
        
        // POST: Beers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("ID,Name,ABV,StyleID,CountryID,BreweryID,Rating,CreatedOn,ModifiedOn,DeletedOn,IsDeleted")] Beer beer)
        {
            if (id != beer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(beer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BeerExists(beer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreweryID"] = new SelectList(_context.Breweries, "ID", "Name", beer.BreweryID);
            ViewData["CountryID"] = new SelectList(_context.Countries, "ID", "Name", beer.CountryID);
            ViewData["StyleID"] = new SelectList(_context.BeerStyles, "ID", "Description", beer.StyleID);
            return View(beer);
        }
        */

        // GET: Beers/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await this._service.GetAsync(id);
            if (beer == null)
            {
                return NotFound();
            }
            return View(beer.MapBeerDTOToView());

            //return RedirectToAction(nameof(Index));
        }

        // POST: Beers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var result = await this._service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

BeerOverflow/BeerOverflowAPI/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BeerOverflowAPI.Models;
using BeerOverflowAPI.ViewMappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Contracts;

namespace BeerOverflowAPI.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        private readonly ICommentService _service;
        private readonly IReviewsService _reviewService;
        //private readonly IBeerService _beerService;
        private readonly IUsersService _userService;

        public CommentsController(IReviewsService _reviewService, IUsersService _usersService, ICommentService _service)
        {
            this._service = _service ?? throw new ArgumentNullException("Service not found");
            this._reviewService = _reviewService ?? throw new ArgumentNullException("Service not found");
            this._userService = _usersService ?? throw new ArgumentNullException("Service not found");
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}

        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var comment = await _service.GetAsync(id);
        //    if (comment == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(comment.MapDTOToCommentView());
        //}

        public IActionResult Create(int userID, int reviewID)
        {
            ViewData["BeerID"] = _reviewService.GetAsync(reviewID);
            ViewData["UserID"] = _userService.GetUser(userID);
            return View();
        }

        // POST: Review/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ReviewID,UserID,Description,IsDeleted")] CommentViewModel comment)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _service.CreateAsync(comment.MapCommentViewToDTO());
                    return RedirectToAction("Details", "Review", new { id = comment.ReviewID });
                }
                catch (Exception)
                {

                    return RedirectToAction("Index", "Home");
                }
                
            }
            ViewData["Review"] = _reviewService.GetAsync(comment.ReviewID);
            ViewData["UserID"] = _userService.GetUser(comment.UserID);
            return View(comment);
        }
    }
}

BeerOverflow/BeerOverflowAPI/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services;

namespace BeerOverflowAPI.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {

        private readonly IUsersService _service;

        public UsersController(IUsersService service)
        {
            this._service = service ?? throw new ArgumentNullException(nameof(service));
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Drink(int userID, int beerID)
        {
            if (userID <= 0 || beerID == default)
            {
                return BadRequest();
            }

            try
            {
                var model = await this._service.Drink(userID, beerID);
                return RedirectToAction("Details", "Beers", new { id = beerID });
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        public async Task<IActionResult> Wish(int userID, int beerID)
        {
            if (userID <= 0 || beerID == default)
            {
                return BadRequest();
            }

            try
            {
                var model = await this._service.Wish(userID, beerID);
                return RedirectToAction("Details", "Beers", new { id = beerID });
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        public async Task<IActionResult> Like(int userID, int reviewID)
        {
            if (userID <= 0 || reviewID == default)
            {
                return BadRequest();
            }

            try
            {
                var result = await this._service.Like(userID, reviewID);
                return RedirectToAction("Details", "Review", new { id = reviewID });


            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

        public async Task<IActionResult> Flag(int userID, int reviewID)
        {
            if (userID <= 0 || reviewID == default)
            {
                return BadRequest();
            }

            try
            {
                var result = await this._service.Flag(userID, reviewID);
                return RedirectToAction("Details", "Review", new { id = reviewID });
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }
        public async Task<IActionResult> Rate(int userID, int beerID, int rating)
        {

            if (rating <= 0 || beerID == default || userID ==default )
            {
                return BadRequest();
            }

            try
            {
                var model = await this._service.Rate(userID, beerID, rating);
                return RedirectToAction("Details", "Beers", new { id = beerID });
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
        }

    }
}

BeerOverflow/BeerOverflowAPI/Views/Review/Create.cshtml
@model ReviewViewModel

@{
    ViewData["Title"] = "Create";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserID" />
            <input type="hidden" asp-for="BeerID" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="10"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

BeerOverflow/BeerOverflowAPI/Views/Review/Delete.cshtml
@model BeerOverflow.Models.Review

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Review</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Beer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Beer.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LikesCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LikesCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeletedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeletedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsFlagged)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsFlagged)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

BeerOverflow/BeerOverflowAPI/Views/Review/Details.cshtml
@model ReviewViewModel
@using Microsoft.AspNetCore.Identity
@using BeerOverflow.Models

@{
    ViewData["Title"] = "Details";
}
@inject UserManager<User> UserManager

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

    <div>
        <h4>Review</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BeerName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BeerName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.UserName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.UserName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Rating)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Rating)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LikesCount)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LikesCount)
            </dd>
            @*<dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.IsDeleted)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.IsDeleted)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.IsFlagged)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.IsFlagged)
                </dd>*@
        </dl>
    </div>
    <div>
        <a asp-controller="Beers" asp-action="Details" asp-route-id="@Model.BeerID">Back to List</a>
        @if (User.Identity.IsAuthenticated)
        {
            var user = await UserManager.GetUserAsync(User);
            var userId = user.Id;
            <a asp-controller="Comments" asp-action="Create" asp-route-userID="@userId" asp-route-reviewID="@Model.ID">| Write a Comment </a>
            <a asp-controller="Users" asp-action="Like" asp-route-userID="@userId" asp-route-reviewID="@Model.ID">| Like </a>
            @if (!Model.IsFlagged)
            {
                <a asp-controller="Users" asp-action="Flag" asp-route-userID="@userId" asp-route-reviewID="@Model.ID">| Flag </a>
            }
        }
    </div>
    <div>
        <dl class="row">
            @foreach (var item in Model.Comments)
            {
                <dt class="col-sm-2">
                    @Html.DisplayFor(model => item.UserName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => item.Description)
                </dd>
                <dd>
                    @*<a asp-controller="Comments" asp-action="Details" asp-route-id="@item.ID">Details</a>*@
                    @*@if (item.UserName == User.Identity.Name)
                        {
                            <a asp-action="Edit" asp-route-id="@item.ID">| Edit |</a>
                            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                        }*@
                </dd>
            }
        </dl>
    </div>
</body>
</html>

BeerOverflow/BeerOverflowAPI/Views/Review/Edit.cshtml
@model BeerOverflow.Models.Review

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="BeerID" class="control-label"></label>
                <select asp-for="BeerID" class="form-control" asp-items="ViewBag.BeerID"></select>
                <span asp-validation-for="BeerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserID" class="control-label"></label>
                <select asp-for="UserID" class="form-control" asp-items="ViewBag.UserID"></select>
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LikesCount" class="control-label"></label>
                <input asp-for="LikesCount" class="form-control" />
                <span asp-validation-for="LikesCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" />
                <span asp-validation-for="CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedOn" class="control-label"></label>
                <input asp-for="ModifiedOn" class="form-control" />
                <span asp-validation-for="ModifiedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeletedOn" class="control-label"></label>
                <input asp-for="DeletedOn" class="form-control" />
                <span asp-validation-for="DeletedOn" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsFlagged" /> @Html.DisplayNameFor(model => model.IsFlagged)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

BeerOverflow/BeerOverflowAPI/Views/Review/Index.cshtml
@model IEnumerable<BeerOverflow.Models.Review>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Beer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LikesCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeletedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDeleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsFlagged)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Beer.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LikesCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeletedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsFlagged)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>